### ISSUE TITLE
如何上报异常

### ISSUE THREAD

**Issue by evilk123** [hsk99/transfer-statistics#1]
在controller/action中,抛出了异常
但上报数据中,并没有收集到异常

**Comment by hsk99** [comment]
> 在controller/action中，抛出了异常 但上报数据中，并没有收集到异常

在上报数据 详情中 增加信息即可，文档已更新
![image](https://user-images.githubusercontent.com/20775916/147319902-6748c566-3279-4517-9b30-ed43ff05435b.png)

**Comment by evilk123** [comment]
非常感谢
现在,能在trace中,看到异常信息了
但界面中,异常数,还是显示0
![image](https://user-images.githubusercontent.com/16203922/147321885-a0d1bfdc-85d0-437c-b9ee-782495284865.png)
![image](https://user-images.githubusercontent.com/16203922/147321911-86c7ef75-1a1f-424d-984e-693a20dad227.png)

**Comment by hsk99** [comment]
> 非常感谢 现在，能在trace中，发现异常信息了 但界面中，异常数，还是显示0 ![图片](https://user-images.githubusercontent.com/16203922/147321885-a0d1bfdc-85d0-437c-b9ee-782495284865.png) ![图片](https://user-images.githubusercontent.com/16203922/147321911-86c7ef75-1a1f-424d-984e-693a20dad227.png)

文档示例中间件是根据 响应码 来判断的，自定义 code 可在中间件中把 $code    = $response->getStatusCode(); 替换为自定义的 code值

**Comment by evilk123** [comment]
> > 非常感谢 现在，能在trace中，发现异常信息了 但界面中，异常数，还是显示0 ![图片](https://user-images.githubusercontent.com/16203922/147321885-a0d1bfdc-85d0-437c-b9ee-782495284865.png) ![图片](https://user-images.githubusercontent.com/16203922/147321911-86c7ef75-1a1f-424d-984e-693a20dad227.png)
> 
> 文档示例中间件是根据 响应码 来判断的，自定义 code 可在中间件中把 $code = $response->getStatusCode(); 替换为自定义的 code值

非常感谢,已解决
现在尝试新增SQL监控,文档使用的是think-db
我们用的是laravel-db
