### ISSUE TITLE
一次请求,请求数+3

### ISSUE THREAD

**Issue by evilk123** [hsk99/transfer-statistics#3]
有时候1次请求,请求数正常+1
有时候1次请求,请求数会+3
很奇怪

**Comment by evilk123** [comment]
> 有时候1次请求,请求数正常+1 有时候1次请求,请求数会+3 很奇怪

不开启SQL上报,没问题
但一开启SQL上报,就会异常
![image](https://user-images.githubusercontent.com/16203922/147344600-5730a8a0-1a86-4526-bac8-98d9ee126062.png)

**Comment by hsk99** [comment]
> > 1次请求，请求数正常+1 1次请求，请求数会+3 很相似
> 
> 不开启SQL上报,没问题 但一开启SQL上报,出现异常 ![图片](https://user-images.githubusercontent.com/16203922/147344600-5730a8a0-1a86-4526-bac8-98d9ee126062.png)

SQL 监听放在进程启动时执行一次

**Comment by evilk123** [comment]
> > > 1次请求，请求数正常+1 1次请求，请求数会+3 很相似
> > 
> > 
> > 不开启SQL上报,没问题 但一开启SQL上报,出现异常 ![图片](https://user-images.githubusercontent.com/16203922/147344600-5730a8a0-1a86-4526-bac8-98d9ee126062.png)
> 
> SQL 监听放在进程启动时执行一次

感谢回复
已经处理好了
谢谢
